service: weekly-backend

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
          cors: true
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user
          method: put
          cors: true